name: Build and Deploy
on:
  push:
    # se lance uniquement sur un push du main
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      # recupere le code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

          # install node js 16
          # install de node js (version 16 pour le jeu space invaders)
      - name: Install Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

        # install dependencies
      - name: Install Dependencies
        run: npm install

        # compile / build
      - name: Build
        run: npm run build

        # deploiement github pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build